### ISSUE TITLE
Table 3评估结果是基于ANN还是PDB啊

### ISSUE THREAD

**Issue by 2333557** [Neph0s/InCharacter#3]
你好，论文中Table 3评估结果是基于ANN还是PDB啊？
![image](https://github.com/Neph0s/InCharacter/assets/38718478/f8b359e5-ee11-4652-84d0-dc4a20697bbd)

**Comment by Neph0s** [comment]
> For the BFI and 16P, we adopt types
from the PDb and scores from our invited annotators.

这是因为PDb的type来源于更多的数据，但分类的投票比例不能很好地represent具体的分数。
