### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by joyyyhuang** [Neph0s/InCharacter#4]
![image](https://github.com/Neph0s/InCharacter/assets/57990587/b67620f6-f71c-4f8b-b975-975c7c40cd9d)
你好，我在运行代码#python personality_tests.py --eval_method direct_ask --questionnaire_name 16Personalities --character hutao #出现了如上报错，这是为什么呢？
环境信息：
python=3.11
其他包都是按照readme安装的

**Comment by Neph0s** [comment]
看起来是ChatHaruhi里load角色数据时出了问题，很神秘，我没有遇到过这个错误，其他角色可以吗？

**Comment by joyyyhuang** [comment]
![image](https://github.com/Neph0s/InCharacter/assets/57990587/9bd534f7-bf5d-4d23-90ab-bbded67ca8d8)
我测试了5条示例代码，都是同样的报错，会是因为包chatharuhi版本的问题吗？

**Comment by joyyyhuang** [comment]
方便上传一个requirements.txt吗？

**Comment by Neph0s** [comment]
嗯，错误发生在数据集读取里，这里ChatHaruhi的代码我用起来没问题，可能有问题的是datasets？我的datasets是2.16.1

**Comment by Neph0s** [comment]
我已经将README里声明的包放在了一个requirements.txt文件里。
我试着重新创了一个3.10的环境，并安装了这些包，可以正常运行。
我尝试了datasets==2.16.1和2.19.1，都没有问题。

你可以试试将datasets改为这两个版本，或者改用python3.10

**Comment by joyyyhuang** [comment]
好的！十分感谢您的回答。我试一下。

**Comment by joyyyhuang** [comment]
要是requirements里能带上库版本就更好了^_^

**Comment by joyyyhuang** [comment]
Python==3.10.14
torch==2.0.1
datasets==2.16.1
可以跑通了
