### ISSUE TITLE
OpenAI接口地址在哪修改呢

### ISSUE THREAD

**Issue by joyyyhuang** [Neph0s/InCharacter#5]
如果我想要设置openai.base_url，该怎么做呢？

**Comment by Neph0s** [comment]
直接在代码里加就行了，建议加在utils.py里

`if config.get('proxy', None):
	openai.proxy = config['proxy']`

`if config.get('openai_apibase', None):
	openai.api_base = config['openai_apibase']`

原代码里有这2行，也可以设置config里的openai_apibase
